# Provides a base image to build on top of. This image takes some time to
# build since it installs many dependencies. Making it a base image saves
# signficant time when building functional Ansible EDA images

FROM registry.access.redhat.com/ubi9-minimal

RUN microdnf install java-17 python3 gcc python3-devel -y && microdnf clean all && python -m ensurepip --upgrade && pip3 install ansible ansible-rulebook asyncio aiokafka aiohttp aiosignal kubernetes requests ansible-runner wheel

ENV JAVA_HOME="/usr/lib/jvm/jre-17"

RUN ansible-galaxy collection install community.general ansible.eda kubernetes.core sabre1041.eda
