- hosts: localhost
  connection: local
  tasks:
    - name: Print the resource status message
      ansible.builtin.debug:
        msg: "[{{ ansible_eda.event.type }}] {{ ansible_eda.event.resource.kind }} named `{{ ansible_eda.event.resource.metadata.name}}` in the `{{ ansible_eda.event.resource.metadata.namespace}}` namespace at {{ ansible_eda.event.meta.received_at }}"
      