- name: Listen to Pod and Deployment Events
  hosts: all
  execution_strategy: sequential
  sources:
    - sabre1041.eda.k8s:
        kind: Deployment
        namespace: "{{ WATCHED_NS }}"
    - sabre1041.eda.k8s:
        kind: ConfigMap
        api_version: v1
        namespace: "{{ WATCHED_NS }}"
  rules:
    - name: Send Update to Slack
      condition: event.type != "MODIFIED" and event.resource.kind != "Deployment"
      actions:
        - run_playbook:
            name: playbook.to-slack.yaml
        # - print_event:
        #     pretty: true
    - name: Send Update to stdout
      condition: event.type != "MODIFIED" and event.resource.kind == "Deployment"
      actions:
        - run_playbook:
            name: playbook.to-stdout.yaml
        # - print_event:
        #     pretty: true