name: Build Legacy Image using Containerfile
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      legacy: ${{ steps.changes.outputs.legacy }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          legacy:
            - 'legacy/**'

  build-image:
    name: Build Legacy EDA k8s Image
    runs-on: ubuntu-latest
    needs: changes

    if: ${{ (needs.changes.outputs.legacy == 'true') || (github.event_name == 'workflow_dispatch') }}
    steps:
    - uses: actions/checkout@v3

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: k8s-ansible-eda
        tags: legacy
        platforms: linux/amd64
        context: ./legacy
        containerfiles: ./legacy/Dockerfile

    - name: Echo Build Outputs
      run: |
        echo "Image: ${{ steps.build-image.outputs.image }}"
        echo "Tags: ${{ steps.build-image.outputs.tags }}"
        echo "Tagged Image: ${{ steps.build-image.outputs.image-with-tag }}"

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rhdevelopers
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"